import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from "react";
import axios from 'axios';
import { toast, ToastContainer } from 'react-toastify';
import moment from 'moment';

export default function Home() {

  const [number, setNumber] = useState('');

  if (typeof window !== 'undefined') {
    var qs = (function (a) {
      if (a == "") return {};
      var b = {};
      for (var i = 0; i < a.length; ++i) {
        var p = a[i].split('=', 2);
        if (p.length == 1)
          b[p[0]] = "";
        else
          b[p[0]] = decodeURIComponent(p[1].replace(/\+/g, " "));
      }
      return b;
    })(window.location.search.substr(1).split('&'));
    var erpcode = qs["erp"];
    document.addEventListener('DOMContentLoaded', function (event) {
      document.getElementById('erp').value = erpcode;
    });
  }

  const Ordering = (e) => {
    e.preventDefault();
    const time = new Date();
    const parseTime = moment(time).format("HH");

    if (parseTime >= 10) {
      toast("Захиалгыг хугацаа дууссан байна. 10 цаг хүртэл захиалах боломжтой!")
    } else {
      axios.post('/api/order', {
        erpcode: `${erpcode}`,
        quantity: `${number}`
      }).then((res) => {
        if (res.status == 200) {
          toast("Захиалга хийгдлээ!")
          setTimeout(() => {
            window.location.pathname = '/'
          }, 3000);
        } else {
          toast("Алдаа гарлаа!")
        }
      }).catch(function (err) {
        console.log(err)
      })
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ХООЛ ЗАХИАЛГА</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/home.svg" />
      </Head>
      <div className="limiter">
        <div className="container-login100"
        >
          <div className="wrap-login100 p-t-30 p-b-50">
            <span className="login100-form-title p-b-41 mb-5 font-bold">
              Захиалга
            </span>
            <ToastContainer 
              position='top-center'
              autoClose={2000}
              />
            <form className="login100-form validate-form p-b-33 p-t-5" action="">
              <div className="wrap-input100 validate-input" >
              </div>
              <div className="wrap-input100 validate-input" >
                <input className="input100" type="text" id="erp" name="erp" defaultValue={erpcode} placeholder="ERP_CODE" readonly />
                <span className="focus-input100" data-placeholder="Код:"></span>
              </div>

              <div className="wrap-input100 validate-input">
                <input className="input100" type="number" id="quantity" name="quantity" defaultValue={1} onChange={(e) => setNumber(e.target.value)} />
                {/* <!--<input className="input100" type="password" name="pass" placeholder="Password">--> */}
                <span className="focus-input100" data-placeholder="Тоо:"></span>
              </div>

              <div className="container-login100-form-btn m-t-32">
                <button className="login100-form-btn my-4" onClick={Ordering}>
                  Захиалах
                </button>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  )
}
